version: '3.4'

services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=coke
    volumes:
      - 'postgresql_data:/bitnami'

volumes:
  postgresql_data:
    driver: local
